scope: cluster0
name: postgresql0

restapi:
  listen: 192.168.0.12X:8008
  connect_address: 192.168.0.12X:8008

etcd:
  hosts: 192.168.0.123:2379,192.168.0.124:2379,192.168.0.125:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      pg_hba:
        - host replication replicator 192.168.0.123/32 md5
        - host replication replicator 192.168.0.125/32 md5
        - host all all 0.0.0.0/0 md5
      parameters:
        unix_socket_directories: '..'
  initdb:
    - encoding: UTF8
    - data-checksums

postgresql:
  listen: 192.168.0.12X:5432
  connect_address: 192.168.0.12X:5432
  data_dir: /var/lib/pgsql/14/data/postgresql1
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: patroni
    rewind:
      username: rewind_user
      password: rewind_password

tags:
  noloadbalance: false
  clonefrom: false
  nosync: false
  nostream: false
